// Vendors the prebuilt @bloodgpt/widgets artifact into ./vendor so this
// example app can consume it exactly like a published npm package — without
// being part of the bloodgpt-for-business pnpm workspace.
//
// Why vendor instead of `file:`/`link:` the source package?
//   1. The source package.json lists `@repo/analysis-ui: workspace:*`, which
//      only resolves inside the monorepo. It is already *bundled* into the
//      dist (tsup `noExternal`), so the runtime never needs it — but a plain
//      install outside the workspace would choke on the workspace protocol.
//   2. Linking into the monorepo risks a second copy of React (the widget's
//      `react` import would resolve against the monorepo's node_modules),
//      which breaks hooks. Vendoring keeps a single React in this app.
//
// This script copies only what a consumer needs (ESM bundle, types, CSS) and
// writes a sanitized package.json whose deps all resolve from the public
// registry. Re-run it whenever you rebuild the widgets package.
//
//   node scripts/sync-widgets.mjs
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = join(here, "..");

// Where the widgets package lives in the sibling monorepo checkout.
const SRC_PKG = join(
  appRoot,
  "..",
  "bloodgpt-for-business",
  "packages",
  "widgets",
);
const SRC_DIST = join(SRC_PKG, "dist");
const DEST = join(appRoot, "vendor", "@bloodgpt", "widgets");
const DEST_DIST = join(DEST, "dist");

// Files we actually ship to a consumer. We deliberately skip the CJS build
// (Next.js uses ESM) and the multi-MB sourcemaps.
const DIST_FILES = ["index.js", "index.d.ts", "styles.css"];

async function main() {
  // Confirm the source build exists.
  const srcMeta = JSON.parse(
    await readFile(join(SRC_PKG, "package.json"), "utf8"),
  );

  await rm(DEST, { recursive: true, force: true });
  await mkdir(DEST_DIST, { recursive: true });

  for (const file of DIST_FILES) {
    await cp(join(SRC_DIST, file), join(DEST_DIST, file));
  }

  // Sanitized manifest: keep the public-registry deps, drop the bundled
  // workspace package, and re-point exports at the trimmed dist.
  const vendoredPkg = {
    name: srcMeta.name,
    version: srcMeta.version,
    description: srcMeta.description,
    license: srcMeta.license,
    type: "module",
    types: "./dist/index.d.ts",
    module: "./dist/index.js",
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
      "./styles.css": "./dist/styles.css",
    },
    sideEffects: ["**/*.css"],
    // `@repo/analysis-ui` is intentionally omitted — it is bundled into
    // dist/index.js, so it must NOT appear as an install-time dependency.
    dependencies: srcMeta.dependencies
      ? Object.fromEntries(
          Object.entries(srcMeta.dependencies).filter(
            ([name]) => !name.startsWith("@repo/"),
          ),
        )
      : {},
    peerDependencies: srcMeta.peerDependencies ?? {},
    _vendoredFrom: "../bloodgpt-for-business/packages/widgets",
    _vendoredNote:
      "Generated by scripts/sync-widgets.mjs. Do not edit by hand — re-run the script to refresh.",
  };

  await writeFile(
    join(DEST, "package.json"),
    JSON.stringify(vendoredPkg, null, 2) + "\n",
  );

  // Copy the upstream README for reference.
  try {
    await cp(join(SRC_PKG, "README.md"), join(DEST, "README.md"));
  } catch {
    // README is optional.
  }

  console.log(
    `Vendored ${vendoredPkg.name}@${vendoredPkg.version} -> vendor/@bloodgpt/widgets`,
  );
}

main().catch((err) => {
  console.error("sync-widgets failed:", err);
  process.exit(1);
});
